# Metric names in report json file
APPARENT_MATCH_DISTRIBUTION = 'apparent_match_distribution'
CORRELATIONS = 'Correlations'
INCONSISTENCIES = 'inconsistencies'
K_MARGINAL = 'k_marginal'
LINEAR_REGRESSION = 'linear_regression'
PCA = 'pca'
PERCENT_RECORDS_MATCHED_IN_TARGET_DATA = 'percent records matched in target data'
PROPENSITY_MEAN_SQUARE_ERROR = 'propensity mean square error'
UNIQUE_EXACT_MATCHES = 'unique_exact_matches'
UNIVARIATE = 'Univariate'

# Report json file properties
# Not all properties inside a report json file are listed here
AGE = 'age'
CORRELATION_DIFFERENCE = 'correlation_difference'
DATA_DESCRIPTION = 'data_description'
HIGHLIGHTED_PLOTS = 'highlighted_plots'
INCONSISTENCY_NAME = 'inconsistency_name'
INCONSISTENCY_VIOLATIONS = 'inconsistency_violations'
K_MARGINAL_SCORE = 'k_marginal_score'
K_MARGINAL_SYNOPSYS = 'k_marginal_synopsys'
LABELS = 'labels'
MSP_MSP_N_CHILDREN_AGE_LT_15 = 'MSP-MSP_N-Children (AGEP < 15)'
NUMBER_OF_RECORDS_INCONSISTENT = 'Number of Records Inconsistent'
PEARSON_CORRELATION_DIFFERENCE = 'pearson correlation difference'
PERCENT_RECORDS_INCONSISTENT = 'Percent Records Inconsistent'
PLOT = 'plot'
PROPENSITY_DISTRIBUTION = 'propensity_distribution'
SUMMARY = 'summary'

# Name of original target datasets
MA2019 = 'ma2019'
TX2019 = 'tx2019'
NATIONAL2019 = 'national2019'

# Dataset features
PUMA = 'PUMA'
AGEP = 'AGEP'
SEX = 'SEX'
MSP = 'MSP'
HISP = 'HISP'
RAC1P = 'RAC1P'
NOC = 'NOC'
NPF = 'NPF'
HOUSING_TYPE = 'HOUSING_TYPE'
OWN_RENT = 'OWN_RENT'
DENSITY = 'DENSITY'
INDP = 'INDP'
INDP_CAT = 'INDP_CAT'
EDU = 'EDU'
PINCP = 'PINCP'
PINCP_DECILE = 'PINCP_DECILE'
POVPIP = 'POVPIP'
DVET = 'DVET'
DREM = 'DREM'
DPHY = 'DPHY'
DEYE = 'DEYE'
DEAR = 'DEAR'
WGTP = 'WGTP'
PWGTP = 'PWGTP'

# Index file columns
ALGORITHM_NAME = 'algorithm name'
ALGORITHM_TYPE = 'algorithm type'
DATA_PATH = 'data path'
DEID_DATA_ID = 'deid data id'
DELTA = 'delta'
EPSILON = 'epsilon'
FEATURE_SET_NAME = 'feature set name'
FEATURE_SPACE_SIZE = 'feature space size'
FEATURES_LIST = 'features list'
INDEX = 'index'
LABELS_PATH = 'labels path'
LIBRARY_NAME = 'library name'
PRAM_FEATURES = 'pram features'
PRAM_FEATURES_EXCEPTION = 'pram features exception'
PRIVACY_CATEGORY = 'privacy category'
PRIVACY_LABEL_DETAIL = 'privacy label detail'
REPORT_PATH = 'report path'
RESEARCH_PAPERS = 'research papers'
SUBMISSION_NUMBER = 'submission number'
SUBMISSION_TIMESTAMP = 'submission timestamp'
QUASI_IDENTIFIERS_SUBSET = 'quasi identifiers subset'
TARGET_DATASET = 'target dataset'
TEAM = 'team'
VARIANT_LABEL = 'variant label'
VARIANT_LABEL_DETAIL = 'variant label detail'

# Data Source
DEID = 'deid'
TARGET = 'target'

# Others
DEID_SAMPLES = 'Deid. samples'
LABEL = 'label'
TARGET_SAMPLES = 'Target samples'


